name: Patch Version, Sync Crowdin, Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Increment version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch

      - name: Push changes (optional, requires a secret)
        run: |
          git push origin ${{ github.ref }}
          # Consider using a Personal Access Token with limited permissions for pushing
          # See https://docs.github.com/en/actions/guides/using-secrets-with-github-actions for details

  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    needs: version
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: "New Crowdin Translations"
          pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
          pull_request_base_branch_name: "main"

          # Export options
          skip_untranslated_strings: true
          export_only_approved: true

          config: "crowdin.yml"

        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: synchronize-with-crowdin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hewkawar/hstudio-bot:latest -f ./.docker/Dockerfile .

      - name: Push Docker image
        run: docker push hewkawar/hstudio-bot:latest
