name: Patch Version, Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Increment version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch

      - name: Push changes (optional, requires a secret)
        run: |
          git push origin ${{ github.ref }}
          # Consider using a Personal Access Token with limited permissions for pushing
          # See https://docs.github.com/en/actions/guides/using-secrets-with-github-actions for details

  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hewkawar/hstudio-bot:latest -f ./.docker/Dockerfile .

      - name: Push Docker image
        run: docker push hewkawar/hstudio-bot:latest
