name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hewkawar/hstudio-bot:latest -f ./.docker/Dockerfile .
        
      - name: Push Docker image
        run: docker push hewkawar/hstudio-bot:latest

      - name: Login AWS
        run: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 851292282452.dkr.ecr.us-west-1.amazonaws.com
      
      - name: Tage AWS image
        run: docker tag hewkawar/hstudio-bot:latest 851292282452.dkr.ecr.us-west-1.amazonaws.com/hstudio-bot:latest

      - name: Push AWS image
        run: docker push 851292282452.dkr.ecr.us-west-1.amazonaws.com/hstudio-bot:latest