name: Sync Crowdin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin_translations
          create_pull_request: false
          skip_untranslated_strings: true
          export_only_approved: true
          config: crowdin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Check if branch exists and fetch commits
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads origin crowdin_translations; then
            git fetch origin crowdin_translations
            if [ "$(git rev-parse origin/crowdin_translations)" != "$(git rev-parse origin/main)" ]; then
              echo "New commits detected."
              echo "create_pull_request=true" >> $GITHUB_ENV
            else
              echo "No new commits."
              echo "create_pull_request=false" >> $GITHUB_ENV
            fi
          else
            echo "Branch crowdin_translations does not exist."
            echo "create_pull_request=false" >> $GITHUB_ENV
          fi
  
      - name: Create Pull request
        if: env.create_pull_request == 'true'
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CROWDIN_PULLS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/HStudioDiscordBot/HStudioSource/pulls \
          -d '{"title":"New Crowdin Translations","body":"New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)","head":"HStudioDiscordBot:crowdin_translations","base":"main"}'
