name: Version Increment (Patch)

on:
  push:
    branches: [ main ]

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Increment version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch

      # - name: Create a Git tag (optional)
      #   run: |
      #     git tag "v$(node -p "require('./package.json').version")"

      - name: Commit version changes (optional)
        run: |
          git add package.json
          git commit -m "Version bump to $(node -p "require('./package.json').version")"

      - name: Push changes (optional, requires a secret)
        run: |
          git push origin ${{ github.ref }}
          # Consider using a Personal Access Token with limited permissions for pushing
          # See https://docs.github.com/en/actions/guides/using-secrets-with-github-actions for details
          